# Generated by Django 3.2.16 on 2022-11-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20221113_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(help_text='Book name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookinstance', to='catalog.book'),
        ),
    ]
