# Generated by Django 3.2.16 on 2022-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biografy',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
